export const ADD_USER = 'ADD_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const FETCH_CARD_LIST = 'FETCH_CARD_LIST';
export const FETCH_CARD_LIST_RESOLVE = 'FETCH_CARD_LIST_RESOLVE';
export const FETCH_CARD_LIST_REJECT = 'FETCH_CARD_LIST_REJECT';